name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clippy
      run: cargo clippy
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --verbose
